dist: xenial
sudo: required
<<<<<<< HEAD

language: python
python:
  - 3.6
  - 3.7

matrix:
  allow_failures:
    - env: TOXENV=pylint

install:
  - pip install tox-travis
script:
  - tox

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - { stage: lint, python: 3.7, env: TOXENV=flake8 }
    - { stage: lint, python: 3.7, env: TOXENV=pylint }
    - { stage: lint, python: 3.7, env: TOXENV=readme }
    - stage: deploy
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: Bashar.said
        password:
          secure: D99UQ4DWGbwtry9Yyaszw+qZp0Ma4KZKBMFIe1dwzl8XQdRtdH+duQhPJY62OyYhZd2vD8MlAi/gcN5aknQ9P0GA+kcThB9SRdDca5Zmy80JLRE3jkksnCg9EmgjLXMdAjJ9fx14OmjGw6leshu1gptKUnBqcbOEvGJ7jF857bB/TY74LqP1BpB49My2Tw4d6MMt1oOWU4EoILX3cY2lZiVu0X/CvqMnBBNwl48Roi8iWDi7u2nbf9tW29Sw/7iPWUA1wkj044NL96K7eoLNyWlsYyEnvkCfYl1QKKw0TMLvd5G3ht4TgiIOeVN07jtDLohPqGJz5sW0AX98/Xl+1nhKxGax0FLZzTVnh8whQi8OnH89m2MXlt0+sy9RCWEyGWat0m5il+47Ce/WXhNc3expoXkLJ5qnyCz9znm0Nt9gAATxsF5LcafqyYVZA7q9G3CMXrQ92FE+2wYo3GuK/0m+Vj7B+kl6dLyA1urTOoBnKW9wiHLjOIIgcffZ/6j0whwdFYKNb+RVHNFF1KfW1fqpWtJ2h7m4fFP0zIpfZGe94gXtagReawcTvrRwkTUMICdQsQWBdzlTinFq5v3s928898llPHpUocY70rID0KfuYggOK5ZNw+GTnNs+KH/O+zmQgKL3zFc7HjiyNnKCx+dMP0P/Apphz8DyWoVnhBM=
        on:
          tags: true
=======
language: python
python:
- 3.6
- 3.7
matrix:
  allow_failures:
  - env: TOXENV=pylint
install:
- pip install tox-travis
script:
- tox
stages:
- lint
- test
- deploy
jobs:
  include:
  - stage: lint
    python: 3.7
    env: TOXENV=flake8
  - stage: lint
    python: 3.7
    env: TOXENV=pylint
  - stage: lint
    python: 3.7
    env: TOXENV=readme
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: Bashar.said
      password:
        secure: YDP7tWG5w7rbajpnBsJCsvNDtoict7sMiosnwbw6FPoyY+rKfy0LeJeooaLUTmftWxOp3kVyJTSsVO8fCf6ML9eCEu/94FlbJchu32eaDsrlAUcEU8N6bxOhgFRep3d7ZAh7ozfkiuqBq5l+24eYcCf17zEraXfASa8rsaYtrJmjfIeen7wAs9QgfIdQPVm9iY6i1jwW/GHQMXBDyLv9q+KTCXTGNMgDOSCbetOcIUHAfp9/J/LYg6++t0W5nEimihQ5g3RAxfN7s/BVEi2wxDUrzJ6TnUshzfSRwN+RDRHjR/j9tw/CW8WMNcWU38Yc0P3KIYi6Fa9+jjI1tX1tc3ql2Jv9MSLKYJgRr9teJIo4pGp2z120BpCKGBtg/Pi8Cy1Y9DWvBGQHQl+MLWw9Aoj9xlgaDOeLAGdYEDdpRUT1J9BAwej8JDdcyFf5agvZPo2MVCnsTTXhiVAIetdv1YlZ8sEBOGTZvD+2z+gmQyj6c67BxkhxAIQGbG8wVtNsM6n7rH+fhmXOiKOFBvwc0Bk/sztWdiZGFKxKUi70YbiYxJalROSX8ec2wyCmF2WjYRo8Ri024jUIkGv+7982NH3iJAT9c8caAxBgAM2IMj6/h4cDgkY8oSY0q0Jr2VjweFRO/Di+1PmVX8RmfyVy1m+PjmVC9Qi9JYaQc8PA/Mk=
      on:
        tags: true

>>>>>>> feature/add-tox-and-travis
